#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ppp
Version  : 2.4.9
Release  : 16
URL      : https://github.com/paulusmack/ppp/archive/ppp-2.4.9/ppp-2.4.9.tar.gz
Source0  : https://github.com/paulusmack/ppp/archive/ppp-2.4.9/ppp-2.4.9.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1 RSA-MD
Requires: ppp-bin = %{version}-%{release}
Requires: ppp-lib = %{version}-%{release}
Requires: ppp-license = %{version}-%{release}
Requires: ppp-man = %{version}-%{release}
BuildRequires : libpcap-dev
BuildRequires : openssl-dev
Patch1: triple-rot13.patch

%description
Point-to-Point Protocol (PPP) to provide Internet connections over
serial lines.

%package bin
Summary: bin components for the ppp package.
Group: Binaries
Requires: ppp-license = %{version}-%{release}

%description bin
bin components for the ppp package.


%package dev
Summary: dev components for the ppp package.
Group: Development
Requires: ppp-lib = %{version}-%{release}
Requires: ppp-bin = %{version}-%{release}
Provides: ppp-devel = %{version}-%{release}
Requires: ppp = %{version}-%{release}

%description dev
dev components for the ppp package.


%package lib
Summary: lib components for the ppp package.
Group: Libraries
Requires: ppp-license = %{version}-%{release}

%description lib
lib components for the ppp package.


%package license
Summary: license components for the ppp package.
Group: Default

%description license
license components for the ppp package.


%package man
Summary: man components for the ppp package.
Group: Default

%description man
man components for the ppp package.


%prep
%setup -q -n ppp-ppp-2.4.9
cd %{_builddir}/ppp-ppp-2.4.9
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649351024
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
%configure --disable-static
make  %{?_smp_mflags}  COPTS="$CFLAGS"

%install
export SOURCE_DATE_EPOCH=1649351024
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ppp
cp %{_builddir}/ppp-ppp-2.4.9/pppd/plugins/pppoatm/COPYING %{buildroot}/usr/share/package-licenses/ppp/18bfbcc612f7daaeb150e2ef5dad0aec82b80b51
cp %{_builddir}/ppp-ppp-2.4.9/pppd/plugins/radius/COPYRIGHT %{buildroot}/usr/share/package-licenses/ppp/b98c076b7b97562c420880d0d45ec541b7410f9f
%make_install DESTDIR=%{buildroot}/usr
## install_append content
chmod -v 0755 %{buildroot}/usr/lib/pppd/*/*.so
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/chat
/usr/bin/pppd
/usr/bin/pppdump
/usr/bin/pppoe-discovery
/usr/bin/pppstats

%files dev
%defattr(-,root,root,-)
/usr/include/pppd/ccp.h
/usr/include/pppd/chap-new.h
/usr/include/pppd/chap_ms.h
/usr/include/pppd/eap-tls.h
/usr/include/pppd/eap.h
/usr/include/pppd/ecp.h
/usr/include/pppd/eui64.h
/usr/include/pppd/fsm.h
/usr/include/pppd/ipcp.h
/usr/include/pppd/ipv6cp.h
/usr/include/pppd/ipxcp.h
/usr/include/pppd/lcp.h
/usr/include/pppd/magic.h
/usr/include/pppd/md4.h
/usr/include/pppd/md5.h
/usr/include/pppd/mppe.h
/usr/include/pppd/patchlevel.h
/usr/include/pppd/pathnames.h
/usr/include/pppd/pppcrypt.h
/usr/include/pppd/pppd.h
/usr/include/pppd/session.h
/usr/include/pppd/sha1.h
/usr/include/pppd/spinlock.h
/usr/include/pppd/tdb.h
/usr/include/pppd/upap.h

%files lib
%defattr(-,root,root,-)
/usr/lib/pppd/2.4.9/minconn.so
/usr/lib/pppd/2.4.9/openl2tp.so
/usr/lib/pppd/2.4.9/passprompt.so
/usr/lib/pppd/2.4.9/passwordfd.so
/usr/lib/pppd/2.4.9/pppoatm.so
/usr/lib/pppd/2.4.9/pppoe.so
/usr/lib/pppd/2.4.9/pppol2tp.so
/usr/lib/pppd/2.4.9/radattr.so
/usr/lib/pppd/2.4.9/radius.so
/usr/lib/pppd/2.4.9/radrealms.so
/usr/lib/pppd/2.4.9/rp-pppoe.so
/usr/lib/pppd/2.4.9/winbind.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ppp/18bfbcc612f7daaeb150e2ef5dad0aec82b80b51
/usr/share/package-licenses/ppp/b98c076b7b97562c420880d0d45ec541b7410f9f

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/chat.8
/usr/share/man/man8/pppd-radattr.8
/usr/share/man/man8/pppd-radius.8
/usr/share/man/man8/pppd.8
/usr/share/man/man8/pppdump.8
/usr/share/man/man8/pppstats.8
