#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x9E4295D605F66CE9 (paulus@samba.org)
#
Name     : ppp
Version  : 2.4.7
Release  : 1
URL      : https://download.samba.org/pub/ppp/ppp-2.4.7.tar.gz
Source0  : https://download.samba.org/pub/ppp/ppp-2.4.7.tar.gz
Source99 : https://download.samba.org/pub/ppp/ppp-2.4.7.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: ppp-bin = %{version}-%{release}
Requires: ppp-license = %{version}-%{release}
Patch1: triple-rot13.patch

%description
Point-to-Point Protocol (PPP) to provide Internet connections over
serial lines.

%package bin
Summary: bin components for the ppp package.
Group: Binaries
Requires: ppp-license = %{version}-%{release}

%description bin
bin components for the ppp package.


%package license
Summary: license components for the ppp package.
Group: Default

%description license
license components for the ppp package.


%prep
%setup -q -n ppp-2.4.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545240830
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1545240830
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ppp
cp pppd/plugins/pppoatm/COPYING %{buildroot}/usr/share/package-licenses/ppp/pppd_plugins_pppoatm_COPYING
%make_install

%files
%defattr(-,root,root,-)
/include/pppd/ccp.h
/include/pppd/chap-new.h
/include/pppd/chap_ms.h
/include/pppd/eap.h
/include/pppd/ecp.h
/include/pppd/eui64.h
/include/pppd/fsm.h
/include/pppd/ipcp.h
/include/pppd/ipv6cp.h
/include/pppd/ipxcp.h
/include/pppd/lcp.h
/include/pppd/magic.h
/include/pppd/md4.h
/include/pppd/md5.h
/include/pppd/patchlevel.h
/include/pppd/pathnames.h
/include/pppd/pppcrypt.h
/include/pppd/pppd.h
/include/pppd/session.h
/include/pppd/sha1.h
/include/pppd/spinlock.h
/include/pppd/tdb.h
/include/pppd/upap.h
/lib/pppd/2.4.7/minconn.so
/lib/pppd/2.4.7/openl2tp.so
/lib/pppd/2.4.7/passprompt.so
/lib/pppd/2.4.7/passwordfd.so
/lib/pppd/2.4.7/pppoatm.so
/lib/pppd/2.4.7/pppol2tp.so
/lib/pppd/2.4.7/radattr.so
/lib/pppd/2.4.7/radius.so
/lib/pppd/2.4.7/radrealms.so
/lib/pppd/2.4.7/winbind.so
/share/man/man8/chat.8
/share/man/man8/pppd-radattr.8
/share/man/man8/pppd-radius.8
/share/man/man8/pppd.8
/share/man/man8/pppdump.8
/share/man/man8/pppstats.8

%files bin
%defattr(-,root,root,-)
/usr/bin/chat
/usr/bin/pppd
/usr/bin/pppdump
/usr/bin/pppstats

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ppp/pppd_plugins_pppoatm_COPYING
