#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x9E4295D605F66CE9 (paulus@samba.org)
#
Name     : ppp
Version  : 2.4.7
Release  : 8
URL      : https://download.samba.org/pub/ppp/ppp-2.4.7.tar.gz
Source0  : https://download.samba.org/pub/ppp/ppp-2.4.7.tar.gz
Source1 : https://download.samba.org/pub/ppp/ppp-2.4.7.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1 RSA-MD
Requires: ppp-bin = %{version}-%{release}
Requires: ppp-lib = %{version}-%{release}
Requires: ppp-license = %{version}-%{release}
Requires: ppp-man = %{version}-%{release}
Patch1: triple-rot13.patch
Patch2: 50a2997b256e0e0ef7a46fae133f56f60fce539c.patch

%description
PPPoL2TP plugin
===============
The pppol2tp plugin lets pppd use the Linux kernel driver pppol2tp.ko
to pass PPP frames in L2TP tunnels. The driver was integrated into the
kernel in the 2.6.23 release. For kernels before 2.6.23, an
out-of-tree kernel module is available from the pppol2tp-kmod package
in the OpenL2TP project.

%package bin
Summary: bin components for the ppp package.
Group: Binaries
Requires: ppp-license = %{version}-%{release}

%description bin
bin components for the ppp package.


%package dev
Summary: dev components for the ppp package.
Group: Development
Requires: ppp-lib = %{version}-%{release}
Requires: ppp-bin = %{version}-%{release}
Provides: ppp-devel = %{version}-%{release}
Requires: ppp = %{version}-%{release}
Requires: ppp = %{version}-%{release}

%description dev
dev components for the ppp package.


%package lib
Summary: lib components for the ppp package.
Group: Libraries
Requires: ppp-license = %{version}-%{release}

%description lib
lib components for the ppp package.


%package license
Summary: license components for the ppp package.
Group: Default

%description license
license components for the ppp package.


%package man
Summary: man components for the ppp package.
Group: Default

%description man
man components for the ppp package.


%prep
%setup -q -n ppp-2.4.7
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568040615
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1568040615
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ppp
cp pppd/plugins/pppoatm/COPYING %{buildroot}/usr/share/package-licenses/ppp/pppd_plugins_pppoatm_COPYING
cp pppd/plugins/radius/COPYRIGHT %{buildroot}/usr/share/package-licenses/ppp/pppd_plugins_radius_COPYRIGHT
%make_install DESTDIR=%{buildroot}/usr
## install_append content
chmod 0755 %{buildroot}/usr/lib/pppd/2.4.7/*.so
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/chat
/usr/bin/pppd
/usr/bin/pppdump
/usr/bin/pppoe-discovery
/usr/bin/pppstats

%files dev
%defattr(-,root,root,-)
/usr/include/pppd/ccp.h
/usr/include/pppd/chap-new.h
/usr/include/pppd/chap_ms.h
/usr/include/pppd/eap.h
/usr/include/pppd/ecp.h
/usr/include/pppd/eui64.h
/usr/include/pppd/fsm.h
/usr/include/pppd/ipcp.h
/usr/include/pppd/ipv6cp.h
/usr/include/pppd/ipxcp.h
/usr/include/pppd/lcp.h
/usr/include/pppd/magic.h
/usr/include/pppd/md4.h
/usr/include/pppd/md5.h
/usr/include/pppd/patchlevel.h
/usr/include/pppd/pathnames.h
/usr/include/pppd/pppcrypt.h
/usr/include/pppd/pppd.h
/usr/include/pppd/session.h
/usr/include/pppd/sha1.h
/usr/include/pppd/spinlock.h
/usr/include/pppd/tdb.h
/usr/include/pppd/upap.h

%files lib
%defattr(-,root,root,-)
/usr/lib/pppd/2.4.7/minconn.so
/usr/lib/pppd/2.4.7/openl2tp.so
/usr/lib/pppd/2.4.7/passprompt.so
/usr/lib/pppd/2.4.7/passwordfd.so
/usr/lib/pppd/2.4.7/pppoatm.so
/usr/lib/pppd/2.4.7/pppol2tp.so
/usr/lib/pppd/2.4.7/radattr.so
/usr/lib/pppd/2.4.7/radius.so
/usr/lib/pppd/2.4.7/radrealms.so
/usr/lib/pppd/2.4.7/rp-pppoe.so
/usr/lib/pppd/2.4.7/winbind.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ppp/pppd_plugins_pppoatm_COPYING
/usr/share/package-licenses/ppp/pppd_plugins_radius_COPYRIGHT

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/chat.8
/usr/share/man/man8/pppd-radattr.8
/usr/share/man/man8/pppd-radius.8
/usr/share/man/man8/pppd.8
/usr/share/man/man8/pppdump.8
/usr/share/man/man8/pppstats.8
